#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# Context environment

# FLOW
FLOW_CONTEXT=Production
FLOW_PATH_TEMPORARY_BASE=/opt/tmp
VIRTUAL_HOST=neos.docker
VIRTUAL_PORT=80
